# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RKSocialLogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RKSocialLogin
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'Google/SignIn'
  target 'RKSocialLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RKSocialLoginUITests' do
    # Pods for testing
  end

end
